# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee22c207669568cc0200a1e1d336a3f93a7002400f9699f93b83bf6c50877bef778ed4122aaacda88d79a35140dfc6d70ff1a4626098c44e5dd4bdb043856194

test:
  secret_key_base: 6d9d215d212cd03f94f77a65a3e8dee6e4f63f8c522e9e80520da396d36d603a85cc7eedb1944f9b812c73ab8cc58b14d5704f488854a65dd5d7a34e080b03e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
